networks:
  - host: "127.0.0.1"
    ssl: false
    public-api-port: 8080
    private-api-port: 8081

deadline_height: 20000

runtimes:
  java: 1

plugins:
  runtime:
    java: "exonum_java_runtime_plugin.JavaDeploySpecLoader"
  artifact:
    timestamping: "exonum_instance_configuration_plugin.InstanceSpecLoader"

artifacts:
  cryptocurrency:
    runtime: java
    name: "com.exonum.examples:cryptocurrency:0.9.0-rc1"
    spec:
      artifact_filename: "exonum-java-binding-cryptocurrency-demo-0.9.0-rc1-artifact.jar"
  time:
    runtime: rust
    name: "exonum-time:0.13.0-rc.2"
  timestamping:
    runtime: rust
    name: "exonum-timestamping:0.13.0-rc.2"

instances:
  cryptocurrency:
    artifact: cryptocurrency
  time:
    artifact: time
  timestamping:
    artifact: timestamping
    config:
      sources: "proto_sources"
      config_message_source: "service.proto"
      message_name: "Config"
      data:
        time_service_name: "time"
